# Generated by Django 4.0.4 on 2022-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettingmodel',
            name='age',
            field=models.IntegerField(blank=True, default=1962),
            preserve_default=False,
        ),
    ]
