# Generated by Django 4.0.4 on 2022-06-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moderators', '0004_usersettingmodel_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingmodel',
            name='age',
        ),
    ]
