# Generated by Django 4.0.4 on 2022-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderators', '0005_remove_usersettingmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettingmodel',
            name='age',
            field=models.IntegerField(default=1962),
            preserve_default=False,
        ),
    ]
